services:  
  catalogdb:  
    container_name: catalogdb  
    environment:  
        - POSTGRES_USER=postgres  
        - POSTGRES_PASSWORD=postgres  
        - POSTGRES_DB=CatalogDb  
    restart: always  
    ports:  
        - "5433:5432"  
    volumes:  
        - postgres_catalog:/var/lib/postgresql/data/  
    healthcheck:  
        test: ["CMD-SHELL", "pg_isready -U postgres"]  
        interval: 10s  
        timeout: 5s  
        retries: 5  

  distributedcache:  
    container_name: distributedcache  
    image: redis:latest   
    restart: always  
    ports:   
        - "6379:6379"  

  orderdb:  
    container_name: orderdb  
    environment:  
        - POSTGRES_USER=postgres  
        - POSTGRES_PASSWORD=postgres  
        - POSTGRES_DB=OrderDB  
    restart: always  
    ports:  
        - "5432:5432"  
    volumes:  
        - postgres_order:/var/lib/postgresql/data/  
    healthcheck:  
        test: ["CMD-SHELL", "pg_isready -U postgres"]  
        interval: 10s  
        timeout: 5s  
        retries: 5  

  messagebroker:  
    container_name: messagebroker  
    hostname: ecommerce-mq
    environment:  
      - RABBITMQ_DEFAULT_USER=jv01  
      - RABBITMQ_DEFAULT_PASS=jv@123  
    restart: always  
    ports:  
      - "5672:5672"  
      - "15672:15672" 
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5 

  catalog.api:  
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_HTTP_PORTS=8080  
      - ASPNETCORE_HTTPS_PORTS=8081  
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true  
    depends_on:  
      - catalogdb  
    ports:  
      - "6000:8080"  
      - "6060:8081"  
    volumes:  
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  

  ordering.api:  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_HTTP_PORTS=8080  
      - ASPNETCORE_HTTPS_PORTS=8081  
      - ConnectionStrings__Database=Server=orderdb;Port=5432;Database=OrderDB;User Id=postgres;Password=postgres;Include Error Detail=true  
      - MessageBroker__Host=amqp://ecommerce-mq:5672  
      - MessageBroker__UserName=jv01  
      - MessageBroker__Password=jv@123  
    ports:  
      - "6003:8080"  
      - "6063:8081"  
    depends_on:  
      orderdb:  
        condition: service_healthy  
      messagebroker:  
        condition: service_healthy  
    volumes:  
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  basket.api:  
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_HTTP_PORTS=8080  
      - ASPNETCORE_HTTPS_PORTS=8081  
      - ConnectionStrings__Redis=distributedcache:6379  
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081  
      - MessageBroker__Host=amqp://ecommerce-mq:5672  
      - MessageBroker__UserName=jv01  
      - MessageBroker__Password=jv@123  
    depends_on:  
      - distributedcache  
      - discount.grpc  
      - messagebroker  
    ports:  
      - "6001:8080"  
      - "6061:8081"  
    volumes:  
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  

  discount.grpc:  
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_HTTP_PORTS=8080  
      - ASPNETCORE_HTTPS_PORTS=8081  
      - ConnectionStrings__Database=Data Source=discountdb  
    depends_on:  
      - distributedcache  
    ports:  
      - "6002:8080"  
      - "6062:8081"  
    volumes:  
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  